### ISSUE TITLE
D2H style guide

### ISSUE THREAD

**Issue by mageshravi** [Webinative/keyframes#5]
Covert the Figma style guide into HTML & CSS (use KSS).

**Comment by vigneshwaran-selvaraj** [comment]
# Alpha testing.

## Base.
![localhost_8002_styleguide_section-base html](https://github.com/user-attachments/assets/c447348d-5a99-4882-b2ce-e3c293b83b55)

## Buttons
![localhost_8002_styleguide_section-buttons html](https://github.com/user-attachments/assets/e8d75e35-a751-454a-970f-eb5df8605016)

## Checkbox
![localhost_8002_styleguide_section-checkbox html](https://github.com/user-attachments/assets/210c480d-eb27-474d-878c-93e0c41d24ba)

## Dialogs
> The overlay is restricted using KSS.

![localhost_8002_styleguide_section-dialog html](https://github.com/user-attachments/assets/b80a7fad-0658-4301-ad49-d71322b5f675)
![localhost_8002_styleguide_section-dialog html (1)](https://github.com/user-attachments/assets/18708ff5-a198-4bbc-84f4-84f40de5d01f)

## Messages.
![localhost_8002_styleguide_section-messages html](https://github.com/user-attachments/assets/b6e5bcc1-1e90-41ab-8065-fca06764a32c)

## Radio buttons.
![localhost_8002_styleguide_section-radio html](https://github.com/user-attachments/assets/c1829b5a-07ef-419b-b73a-c17c3072e8fc)

## select menu.
![localhost_8002_styleguide_section-selectmenu html](https://github.com/user-attachments/assets/ca841a9a-402e-4c1a-bd39-3e5c6943a1a7)

## Textbox and textarea.
![localhost_8002_styleguide_section-textbox html](https://github.com/user-attachments/assets/833ad45e-3339-4aa6-bd8f-edfc95fde565)
![localhost_8002_styleguide_section-textarea html](https://github.com/user-attachments/assets/9524485b-03fd-44d9-b168-4635b00e1036)

**Comment by vigneshwaran-selvaraj** [comment]
# Alpha testing.

![localhost_8002_styleguide_section-pagination html (1)](https://github.com/user-attachments/assets/fcba6fc2-f1fb-4ab5-8c0f-0223d8a08d24)
![localhost_8002_styleguide_section-segmentedcontrol html](https://github.com/user-attachments/assets/5e0e1fcf-ea33-4f94-a4a4-0eaf4068a75d)
